---
id: sapporoonga-20150614
base_name: groonga-family-2015-in-sapporo
tags:
- rabbit
- groonga
presentation_date: 2015-06-14
version: 2015.6.14.2
licenses:
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
